In [1]:
# you need to install chromedriver

import selenium
from selenium import webdriver
import bs4
import lxml
import pandas as pd
import time

In [2]:
# init dataframe
# sentiment gonna be caculated by specific method has standard
df = pd.DataFrame(columns=['id','title','review','score','sentiment'])
df

Empty DataFrame
Columns: [id, title, review, score, sentiment]
Index: []

In [3]:
# get naver movie reviews
base_url = 'https://movie.naver.com/movie/point/af/list.naver'

# execute chrome web driver
driver = webdriver.Chrome('./chromedriver.exe')

In [4]:
for p in range(1,1001):
    driver.get(''.join([base_url,'?&page=',str(p)])) # get target page
    driver.implicitly_wait(time_to_wait=3) # in second
    
    html = bs4.BeautifulSoup(driver.page_source,'lxml')
    reviews:bs4.element.ResultSet = html.find('table',{'class':'list_netizen'}).find('tbody').find_all('tr')
    
    lst = []
    # get id, title, review text and score
    for r in reviews:
        ac_num = r.find('td',{'class':'ac num'}).text
        t = r.find('td',{'class':'title'})
        title = t.find('a').text
        score = float(t.find('em').text)
        
        t.a.decompose()
        t.span.decompose()
        t.div.decompose()
        t.br.decompose()
        t.a.decompose()
        
        text = t.get_text(strip=True)
        
        lst.append([ac_num,title,text,score,None])
    df = pd.concat([df,pd.DataFrame(lst,columns=['id','title','review','score','sentiment'])],ignore_index=True)

driver.close()

df.to_csv()
df

,id,title,review,score,sentiment
0,17998769,반지의 제왕: 왕의 귀환,판타지를 넘어 영화 역사에 남을 명작이다. 내가 이걸 왜 극장에서 못봤을까.... ...,10.0,None
1,17998767,나일 강의 죽음,이집트여행하는느낌의 영화,8.0,None
2,17998766,킹메이커,목포 연설 장면은 넋을 잃고 보게 된다.,10.0,None
3,17998765,기억의 밤,그저 그렇네요. 뻔한 반전과 결말.,4.0,None
4,17998764,더 배트맨,더 배트맨 조커처럼 몰입감이 있으면 추천 반대로 지루하면 비추천,1.0,None
...,...,...,...,...,...
9995,17988421,오! 수정,이해할 수 없는 남자와 이해해주는 여자,7.0,None
9996,17988420,이상한 나라의 수학자,배우들 연기력이 장난아님. 역시 최민식 배우는 클라스가 다름!,10.0,None
9997,17988419,블랙라이트,그래도 최근에 나왔던 영화들에 비해 내용이 되게 흥미진진했음 리암 니슨이 덜뛰는 대...,10.0,None
9998,17988418,더 배트맨,누구나 시작은 어설픈 법. 그래서 더 매력적인 히어로,10.0,None
9999,17988417,달라스 바이어스 클럽,병과 싸우기 위해서는 공부해야 한다,7.0,None

In [5]:
df.to_csv(''.join(['./data/reviews_',str(int(time.time())),'.csv']),index=False)